### ISSUE TITLE
dataset question

### ISSUE THREAD

**Issue by zjin-lcf** [hpg-cepetro/IPDPS-CRS-CMP-code#1]
Can you please provide some dataset for running your programs ?

Thanks

**Comment by eborin** [comment]
Dear Zjin-lcf,

could please provide an e-mail so I can share a link to a folder?

Regards,

--
Prof. Edson Borin
Institute of Computing
Unicamp

**Comment by zjin-lcf** [comment]
I will close the issue and send you an email. Thanks.
